### ISSUE TITLE
Exposed Twitter and Tumbler API Key in scripts/rip.properties

### ISSUE THREAD

**Issue by AstralJaeger** [alex000kim/nsfw_data_scraper#53]
You have two API keys for ripme exposed in the ``scripts/rip.properties`` file.

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。

**Comment by longems** [comment]
收到啦~~陆云龙

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by longems** [comment]
收到啦~~陆云龙

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yyarrow** [comment]
您好，我是元棪，您的邮件已经收到。

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！
